// Script untuk generate PDF dari file teks
const fs = require('fs');
const PDFDocument = require('pdfkit');

// Baca file teks
const pricelistText = fs.readFileSync('./assets/files/mozdeo-pricelist.txt', 'utf8');

// Buat PDF baru
const doc = new PDFDocument({
    size: 'A4',
    margins: {
        top: 50,
        bottom: 50,
        left: 50,
        right: 50
    }
});

// Pipe ke file output
doc.pipe(fs.createWriteStream('./wwwroot/assets/files/mozdeo-pricelist.pdf'));

// Header
doc.fontSize(18)
   .fillColor('#2563EB')
   .text('MOZDEO - DAFTAR HARGA LAYANAN', 50, 50, { align: 'center' });

doc.fontSize(14)
   .fillColor('#2563EB')
   .text('CUCI SEPATU PREMIUM', 50, 75, { align: 'center' });

// Garis pemisah
doc.moveTo(50, 100)
   .lineTo(545, 100)
   .strokeColor('#2563EB')
   .stroke();

// Content
let yPosition = 120;
const lines = pricelistText.split('\n');

lines.forEach((line, index) => {
    if (index < 2) return; // Skip header yang sudah dibuat
    
    if (line.includes('LAYANAN UTAMA:') || line.includes('LAYANAN TAMBAHAN:') || 
        line.includes('PAKET HEMAT:') || line.includes('MEMBER BENEFITS:') || 
        line.includes('CONTACT INFO:')) {
        // Section headers
        doc.fontSize(14)
           .fillColor('#2563EB')
           .text(line, 50, yPosition);
        yPosition += 20;
    } else if (line.match(/^\d+\./)) {
        // Service items
        doc.fontSize(12)
           .fillColor('#000000')
           .text(line, 50, yPosition);
        yPosition += 15;
    } else if (line.startsWith('   -') || line.startsWith('- ')) {
        // Sub items
        doc.fontSize(10)
           .fillColor('#666666')
           .text(line, 70, yPosition);
        yPosition += 12;
    } else if (line.trim() !== '' && !line.includes('===')) {
        // Regular text
        doc.fontSize(11)
           .fillColor('#000000')
           .text(line, 50, yPosition);
        yPosition += 14;
    }
    
    // New page if needed
    if (yPosition > 750) {
        doc.addPage();
        yPosition = 50;
    }
});

// Footer
doc.fontSize(8)
   .fillColor('#999999')
   .text('Generated by Mozdeo System', 50, 780, { align: 'center' });

// Finalize PDF
doc.end();

console.log('PDF berhasil dibuat: ./wwwroot/assets/files/mozdeo-pricelist.pdf');